### ISSUE TITLE
Creating a demo in Stack(for example)

### ISSUE THREAD

**Issue by FelipeSulser** [HaritzPuerto/DataStructuresInScala#15]
I'm having an issue while creating a demo for the stack.

This is what i would like to do:

`var stack = NonEmptyStack[String]("AAAAA",null)`
`stack = stack.push("BBBBB")`

But it doesnt work since stack.push returns a Stack and `var stack` is of type `NonEmptyStack`
how could I use the datastructure then? I dont understand.

Link to the stack: https://github.com/HaritzPuerto/DataStructuresInScala/blob/stack/src/main/scala/stack/NonEmptyStack.scala

**Comment by HaritzPuerto** [comment]
@FelipeSulser 
First of all, I think your code is wrong. It should be:
```
    var stack = new NonEmptyStack[String]("AAAAA",EmptyStack)
    stack = stack.push("BBBBB")
```
Watch out with null values, I don't deal with them in the implementation. I use EmptyStack.

But this still fails...
Nevertheless, this compiles!
``
    var stack = new NonEmptyStack[String]("AAAAA",EmptyStack).push("CCC")
    stack = stack.push("BBBBB")
```

**Comment by FelipeSulser** [comment]
Thanks you are right! Stack problem solved!
