### ISSUE TITLE
Error: Could not find or load main class set.SetDriver2

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/DataStructuresInScala#18]
@zeronone 
I have created a new Driver for doing some tests with sets, your tests seems to work, so there is a problem with my implementation.

```
package set

/**
 * @author haritz
 */
object SetDriver2 {
    def main(args:Array[String]) {
      println(EmptySet.delete(0).isEmpty())  
      println(new NonEmptyLinearSet(1,EmptySet).delete(5).contains(1))
    }
}
```
When I execute this object I obtain an error: Error: Could not find or load main class set.SetDriver2

Do you know what is going on? Thxn

**Comment by zeronone** [comment]
@HaritzPuerto which branch is it? I checked the `set` branch but couldn't find the code.

**Comment by zeronone** [comment]
@HaritzPuerto  You can try the following and make sure that the filename and object name matches.
```scala
object SetDriver extends App {
  println(EmptySet.delete(0).isEmpty())  
  println(new NonEmptyLinearSet(1,EmptySet).delete(5).contains(1))
}
```

**Comment by zeronone** [comment]
@HaritzPuerto I updated the set branch #13 . Now the tests are working and also the `Driver` object. Take a look at the commit.

**Comment by HaritzPuerto** [comment]
I don't know why, but it works now. Thank you!
