### ISSUE TITLE
SBT support

### ISSUE THREAD

**Issue by zeronone** [HaritzPuerto/DataStructuresInScala#4]
I would like to add SBT support. It is not only good for running tests etc. But also when you import the project on other computers, the IDE automatically recognizes the program structure. 

Currently, I can't import the project into ScalaIDE, or is there any way?

**Comment by HaritzPuerto** [comment]
I have no idea of how to do that... I just pull the files. Please, do it if you want and tells us how it works. Thnx
Please note, I have just change the organization of the code, now I have src folder in the root. So we can add a tests folder in the root

**Comment by zeronone** [comment]
I will try to do it :)

**Comment by HaritzPuerto** [comment]
http://www.scala-sbt.org/release/tutorial/es/Hello.html
@FelipeSulser This will be helpful for us
